# Attempt Number 2 - changing the preprocessing

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

In [2]:
#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [7]:
# Drop the non-beneficial ID columns, 'EIN'.
application_df = application_df.drop(['EIN'], axis=1)
application_df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

What would happen if "NAME" remained, but was filtered somehow?

In [4]:
# Look at the name column
name_counts = application_df['NAME'].value_counts()
name_counts

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [6]:
# Name counts greater than 10
name_counts[name_counts>10]

PARENT BOOSTER USA INC                                                    1260
TOPS CLUB INC                                                              765
UNITED STATES BOWLING CONGRESS INC                                         700
WASHINGTON STATE UNIVERSITY                                                492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                            408
                                                                          ...
USA SWIMMING INC                                                            11
SIGMA ALPHA OMEGA CHRISTIAN SORORITY INC                                    11
SOCIETY FOR PRESERVATION & ENCOURMT OF BARBERSHOP QUARTET SINGING AMER      11
SONS OF ITALY IN AMERICA                                                    11
FELLOWSHIP OF CHRISTIAN COWBOYS INC                                         11
Name: NAME, Length: 204, dtype: int64

In [10]:
# Determine which values to replace if counts are less than or equal to 10.
names_to_replace = list(name_counts[name_counts <= 10].index)

# Replace in dataframe
for name in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                     21202
PARENT BOOSTER USA INC                                                     1260
TOPS CLUB INC                                                               765
UNITED STATES BOWLING CONGRESS INC                                          700
WASHINGTON STATE UNIVERSITY                                                 492
                                                                          ...
AMERICAN POSTAL WORKERS UNION                                                11
SOCIETY FOR PRESERVATION & ENCOURMT OF BARBERSHOP QUARTET SINGING AMER       11
SIGMA ALPHA OMEGA CHRISTIAN SORORITY INC                                     11
FINANCIAL PLANNING ASSOCIATION                                               11
SLOW FOOD U S A INC                                                          11
Name: NAME, Length: 205, dtype: int64

In [11]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                       205
APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [12]:
# Look at APPLICATION_TYPE value counts for binning
app_type_counts = application_df['APPLICATION_TYPE'].value_counts()
app_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [13]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_type_counts[app_type_counts < 500].index)

In [14]:

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

In [15]:
# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [16]:
# Look at CLASSIFICATION value counts for binning
class_counts = application_df['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [17]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts_cleaned = class_counts.loc[class_counts > 1]
class_counts_cleaned

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [18]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts < 100].index)

In [19]:
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

In [20]:
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [21]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALPHA PHI SIGMA,NAME_ALPHA PHI SIGMA INC,NAME_ALTRUSA INTERNATIONAL FOUNDATION INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [22]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
y = application_df['IS_SUCCESSFUL'].values

In [23]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 24)

In [24]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

## Optimization Number 4
Changed the data in preprocessing

In [25]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 100
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 10
hidden_nodes_layer4 = 1

nn1 = tf.keras.models.Sequential()

In [26]:
# First hidden layer
nn1.add(tf.keras.layers.Dense(units = hidden_nodes_layer1, input_dim = num_input_features, activation ="relu"))

# Second hidden layer
nn1.add(tf.keras.layers.Dense(units = hidden_nodes_layer2, activation ="tanh"))

# Third hidden layer
nn1.add(tf.keras.layers.Dense(units = hidden_nodes_layer3, activation ="sigmoid"))

# Output layer
nn1.add(tf.keras.layers.Dense(units = hidden_nodes_layer4, activation ="sigmoid"))

In [27]:
# Check the structure of the model
nn1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               25500

 dense_1 (Dense)             (None, 30)                3030

 dense_2 (Dense)             (None, 10)                310

 dense_3 (Dense)             (None, 1)                 11

=================================================================
Total params: 28851 (112.70 KB)
Trainable params: 28851 (112.70 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [28]:
# Compile the model
nn1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [29]:
# Train the model
fit_model = nn1.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.4985 - accuracy: 0.7682
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4566 - accuracy: 0.7827
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4479 - accuracy: 0.7847
Epoch 4/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4436 - accuracy: 0.7857
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4411 - accuracy: 0.7864
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4397 - accuracy: 0.7865
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4382 - accuracy: 0.7876
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4367 - accuracy: 0.7883
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4357 - accuracy: 0.7886
Epoch 10/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4348 - accuracy: 0.7879
Epoch 11/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4340 - accuracy: 0.7891
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4327 - accuracy: 0.7898
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4322 - accuracy: 0.7921
Epoch 14/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4318 - accuracy: 0.7908
Epoch 15/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4312 - accuracy: 0.7913
Epoch 16/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4303 - accuracy: 0.7910
Epoch 17/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4300 - accuracy: 0.7914
Epoch 18/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4294 - accuracy: 0.7917
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4290 - accuracy: 0.7925
Epoch 20/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4290 - accuracy: 0.7919
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4276 - accuracy: 0.7933
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4280 - accuracy: 0.7935
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4272 - accuracy: 0.7938
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4269 - accuracy: 0.7933
Epoch 25/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4266 - accuracy: 0.7947
Epoch 26/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4259 - accuracy: 0.7950
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4255 - accuracy: 0.7952
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4255 - accuracy: 0.7948
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4252 - accuracy: 0.7952
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4251 - accuracy: 0.7952
Epoch 31/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4250 - accuracy: 0.7959
Epoch 32/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4240 - accuracy: 0.7961
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4244 - accuracy: 0.7966
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4238 - accuracy: 0.7950
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4234 - accuracy: 0.7956
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4232 - accuracy: 0.7964
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4228 - accuracy: 0.7967
Epoch 38/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4231 - accuracy: 0.7958
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4232 - accuracy: 0.7956
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4231 - accuracy: 0.7962
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4229 - accuracy: 0.7958
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4226 - accuracy: 0.7963
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4227 - accuracy: 0.7963
Epoch 44/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4229 - accuracy: 0.7966
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4222 - accuracy: 0.7972
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4223 - accuracy: 0.7965
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4222 - accuracy: 0.7966
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4220 - accuracy: 0.7972
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4213 - accuracy: 0.7965
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4212 - accuracy: 0.7971
Epoch 51/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4213 - accuracy: 0.7970
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4216 - accuracy: 0.7961
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4211 - accuracy: 0.7969
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4211 - accuracy: 0.7979
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4208 - accuracy: 0.7972
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4206 - accuracy: 0.7972
Epoch 57/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4205 - accuracy: 0.7968
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4203 - accuracy: 0.7967
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4208 - accuracy: 0.7955
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4210 - accuracy: 0.7970
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4202 - accuracy: 0.7968
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4201 - accuracy: 0.7970
Epoch 63/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4204 - accuracy: 0.7979
Epoch 64/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4205 - accuracy: 0.7968
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4201 - accuracy: 0.7968
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4196 - accuracy: 0.7973
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4195 - accuracy: 0.7973
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4206 - accuracy: 0.7969
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4196 - accuracy: 0.7983
Epoch 70/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4201 - accuracy: 0.7974
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4195 - accuracy: 0.7984
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4196 - accuracy: 0.7987
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4195 - accuracy: 0.7963
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4199 - accuracy: 0.7974
Epoch 75/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4197 - accuracy: 0.7977
Epoch 76/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4193 - accuracy: 0.7977
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4197 - accuracy: 0.7975
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4196 - accuracy: 0.7982
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4201 - accuracy: 0.7978
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4196 - accuracy: 0.7981
Epoch 81/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4193 - accuracy: 0.7979
Epoch 82/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4195 - accuracy: 0.7975
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4201 - accuracy: 0.7984
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4204 - accuracy: 0.7966
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4200 - accuracy: 0.7976
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4199 - accuracy: 0.7978
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4192 - accuracy: 0.7987
Epoch 88/100
804/804 [==============================] - 4s 4ms/step - loss: 0.4190 - accuracy: 0.7987
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4195 - accuracy: 0.7978
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4199 - accuracy: 0.7978
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4197 - accuracy: 0.7982
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4191 - accuracy: 0.7983
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4195 - accuracy: 0.7981
Epoch 94/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4200 - accuracy: 0.7973
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4198 - accuracy: 0.7975
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4199 - accuracy: 0.7986
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4196 - accuracy: 0.7986
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4195 - accuracy: 0.7987
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4198 - accuracy: 0.7991
Epoch 100/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4203 - accuracy: 0.7975

In [30]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn1.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4520 - accuracy: 0.7838 - 557ms/epoch - 2ms/step
Loss: 0.4520494341850281, Accuracy: 0.783790111541748

In [31]:
# Export our model to HDF5 file
nn1.save('../content/drive/My Drive/Colab Notebooks/AlphabetSoupCharity_Opt4.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(